[project]
name = "accounts-service"
version = "0.1.0"
description = ""
authors = [
    {name = "Lameck Irungu",email = "mugolameck@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
    "django (>=6.0.2,<7.0.0)",
    "djangorestframework (>=3.16.1,<4.0.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "psycopg (>=3.3.2,<4.0.0)",
    "drf-spectacular>=0.27.2,<1.0.0",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)"
]


[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
