# Generated by Django 6.0.2 on 2026-02-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["user_id"], name="payments_pa_user_id_1c2b07_idx"),
        ),
    ]
