# Generated by Django 6.0.2 on 2026-02-08 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_add_payment_user_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_user_id_be07d0_idx',
            old_name='payments_pa_user_id_1c2b07_idx',
        ),
    ]
